// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwaEjia_xgOSRyhcg6oW9Wib5DRX5eOlw',
    appId: '1:486884852152:web:38ef9ae130935f754c4f4d',
    messagingSenderId: '486884852152',
    projectId: 'invoiceinaja-4b9e0',
    authDomain: 'invoiceinaja-4b9e0.firebaseapp.com',
    storageBucket: 'invoiceinaja-4b9e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdTKC5GoaN1ZrB4MCmx5g3a6iOyOVnTtw',
    appId: '1:486884852152:android:5ef6dab8a9e060224c4f4d',
    messagingSenderId: '486884852152',
    projectId: 'invoiceinaja-4b9e0',
    storageBucket: 'invoiceinaja-4b9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvmrEQOpLziWzaFM7KRQzg9hegM8oR14',
    appId: '1:486884852152:ios:84dff1005bb9d3764c4f4d',
    messagingSenderId: '486884852152',
    projectId: 'invoiceinaja-4b9e0',
    storageBucket: 'invoiceinaja-4b9e0.appspot.com',
    iosClientId: '486884852152-8b5bb9147m8d6lh6c0bpqu2cenamcg03.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoiceinaja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALvmrEQOpLziWzaFM7KRQzg9hegM8oR14',
    appId: '1:486884852152:ios:84dff1005bb9d3764c4f4d',
    messagingSenderId: '486884852152',
    projectId: 'invoiceinaja-4b9e0',
    storageBucket: 'invoiceinaja-4b9e0.appspot.com',
    iosClientId: '486884852152-8b5bb9147m8d6lh6c0bpqu2cenamcg03.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoiceinaja',
  );
}
